#!/bin/bash

if [ -f "/var/cache/raspberrylink-last-device" ]; then
  DEVICE_ADDR=$(cat /var/cache/raspberrylink-last-device)
  echo "- Attempting to reconnect to previous bluetooth device: " "$DEVICE_ADDR"
  if [ $MULTIPLE_ADAPTERS -eq 1 ]; then
    printf "select %s\nconnect %s\nexit\n" "$BT_ADAPTER_ADDR" "$DEVICE_ADDR" | bluetoothctl
  else
    printf "connect %s\nexit\n" "$DEVICE_ADDR" | bluetoothctl
  fi
fi
echo "- Attempt Complete: " "$DEVICE_ADDR"