#!/bin/bash

# Modified from https://github.com/balenalabs/balena-sound/blob/master/bluetooth-audio/bluetooth-udev

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

name=$(sed 's/\"//g' <<< $NAME)
if [[ ! $name =~ ^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$ ]]; then exit 0; fi

action=$(expr "$ACTION" : "\([a-zA-Z]\+\).*")

SYSTEM_VOLUME=$(</run/raspberrylink_volume)

case "$action" in
add)
    printf "discoverable off\npairable off\nexit\n" | bluetoothctl
    echo $NAME | tr -d '"' > /var/cache/bluetooth/reconnect_device  # Save the mac address of the last connected device (for reconnect after reboot)
    amixer sset PCM,0 $SYSTEM_VOLUME% > /dev/null &
    amixer sset Digital,0 $SYSTEM_VOLUME% > /dev/null &
    ;;
remove)
    printf "discoverable on\npairable on\nexit\n" | bluetoothctl
    amixer sset PCM,0 $SYSTEM_VOLUME% > /dev/null &
    amixer sset Digital,0 $SYSTEM_VOLUME% > /dev/null &
    ;;
esac