#!/bin/bash

# Modified from https://github.com/balenalabs/balena-sound/blob/master/bluetooth-audio/start.sh

echo "- RaspberryLink Bluetooth Bootstrap Script"

echo "- Setting output volume to " "$SYSTEM_VOLUME"
amixer cset numid=$MIXER_NUMID $SYSTEM_VOLUME > /dev/null &

# Set discoverable timeout
echo "- Setting discoverable timeout"
dbus-send --system --dest=org.bluez --print-reply /org/bluez/hci0 org.freedesktop.DBus.Properties.Set string:'org.bluez.Adapter1' string:'DiscoverableTimeout' variant:uint32:0 > /dev/null

echo "- Becoming discoverable and pairable..."
if [ $MULTIPLE_ADAPTERS -eq 1 ]; then
  printf "select %s\ndiscoverable on\npairable on\nexit\n" "$BT_ADAPTER_ADDR" "$TRUSTED_MAC_ADDRESS" | bluetoothctl > /dev/null
else
  printf "discoverable on\npairable on\nexit\n" | bluetoothctl > /dev/null
fi

# Start bluetooth and audio agent
echo "- Starting Python BlueZ Agent"
/usr/src/raspberrylink/raspilink-bt-agent.py &

echo "- Setting microphone input volume to " "$MICROPHONE_VOLUME"
amixer cset numid=$MIC_MIXER_NUMID $MICROPHONE_VOLUME > /dev/null &

echo "- Disabling hci1 interface (if applicable)"
hciconfig hci1 down > /dev/null 2>&1 # Disable onboard bluetooth if using a bluetooth dongle (onboard interface gets remapped to hci1)
# Put bluetooth interface online
echo "- Bringing hci0 online with name: " "$BLUETOOTH_DEVICE_NAME"
hciconfig hci0 up
hciconfig hci0 name "$BLUETOOTH_DEVICE_NAME"
echo "- Bluetooth interface hci0 online"

# Enable simple pairing (no pin code)
echo "- Enabling SSP (Secure Simple Pairing)"
hciconfig hci0 sspmode 1  # Secure Simple Pairing

# Reconnect if there is a known device
sleep 2
if [ -f "/var/cache/raspberrylink_last-device" ]; then
  TRUSTED_MAC_ADDRESS=$(cat /var/cache/raspberrylink_last-device)
  echo "- Attempting to reconnect to previous bluetooth device: " "$TRUSTED_MAC_ADDRESS"
  if [ $MULTIPLE_ADAPTERS -eq 1 ]; then
    printf "select %s\nconnect %s\nexit\n" "$BT_ADAPTER_ADDR" "$TRUSTED_MAC_ADDRESS" | bluetoothctl > /dev/null
  else
    printf "connect %s\nexit\n" "$TRUSTED_MAC_ADDRESS" | bluetoothctl > /dev/null
  fi
  sleep 2
fi

echo "- Bootstrap script complete."